### ISSUE TITLE
recyclerview open url

### ISSUE THREAD

**Issue by doblist** [preethikishore/RecyclerVIew#1]
hi
how can recyclerview open defiant  url in ache itme

**Comment by preethikishore** [comment]
I believe this is what you are looking for. 

   holder.visit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                final String website = Details.get("Curl");
                Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(website));
                context.startActivity(browserIntent);
                
            }
        });



I made a small example - You can Refer 

https://github.com/preethikishore/RecyclerViewItem 

Thanks.
